name: Deploy to ECR

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Amazon ECR
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v1

    - name: Extract ECR repository URI
      id: extract-ecr-uri
      run: echo "::set-output name=ecr_uri::$(aws ecr describe-repositories --repository-names projects --region eu-north-1 --query 'repositories[0].repositoryUri' --output text)"
      env:
        AWS_REGION: eu-north-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Build and push Docker image
      run: |
        docker build -t fastapi-housing .
        docker tag fastapi-housing:latest ${{ steps.extract-ecr-uri.outputs.ecr_uri }}:latest
        docker push ${{ steps.extract-ecr-uri.outputs.ecr_uri }}:latest
      env:
        AWS_REGION: eu-north-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
